"""Build the browser-only course bundle: static/data.js.

The hosted site is fully static and never runs Python — this script is a
*build-time* helper only. It reads the same content modules the dev server
uses, renders every [[diag:...]] placeholder to inline SVG, and writes one
JavaScript file containing the entire course (31 chapters, 61 lessons,
110 quiz questions, 37 diagrams). The web app then needs no backend at all.

Usage:
    python build_static.py          # write static/data.js
    python build_static.py --check  # validate content, exit without writing
"""

import json
import os
import sys

import content  # assembles + validates chapters (imports diagrams)


OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "static", "data.js")


def to_js(chapters):
    """Serialize the course to a JS snippet (JSON with `</` escaped)."""
    payload = json.dumps(
        {"chapters": chapters}, ensure_ascii=False, separators=(",", ":"))
    # `\/` is a valid JSON escape; replacing `</` keeps the bundle from
    # ever being able to close the <script> tag it is embedded in.
    payload = payload.replace("</", "<\\/")
    return ("/* Auto-generated by build_static.py - do not edit. */\n"
            "/* Regenerate with: python build_static.py */\n"
            "window.COURSE_DATA = " + payload + ";\n")


def main():
    chapters = content.validate()  # crashes loudly on malformed content
    n_lessons = sum(len(c["lessons"]) for c in chapters)
    n_quiz = sum(len(c["quiz"]) for c in chapters)
    if "--check" in sys.argv[1:]:
        print("content OK: %d chapters, %d lessons, %d quiz questions"
              % (len(chapters), n_lessons, n_quiz))
        return 0

    # build_content() replaces [[diag:...]] placeholders with inline SVG.
    js = to_js(content.build_content())

    # Round-trip sanity: the embedded payload must parse as valid JSON and
    # round-trip to the same number of chapters.
    start = js.index("{")
    end = js.rindex("};") + 1
    parsed = json.loads(js[start:end].replace("<\\/", "</"))
    if len(parsed["chapters"]) != len(chapters):
        raise SystemExit("round-trip check failed")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(js)
    print("wrote %s (%.1f KB, %d chapters)"
          % (OUT, os.path.getsize(OUT) / 1024.0, len(chapters)))
    return 0


if __name__ == "__main__":
    sys.exit(main())